### ISSUE TITLE
Support for IfcStructuralSurfaceMember

### ISSUE THREAD

**Issue by berndhahnebach** [aothms/IfcOpenShell#18]
Hi Thomas, 

Tried to import the shape of a IfcStructuralSurfaceMember which is a IfcFaceSurface from tons of IfcFaceOuterBound. It is a IfcTopologicalRepresentation not IfcShapeRepresentation. It seams create_shape of IfcOpenShell does not support such entries. If been playing a bit. If I change some entries and add it to the IfcSite the shape could be imported. Find the file here: http://forum.freecadweb.org/download/file.php?id=7552  Is there any chance IfcOpenShell is gone support such entries?

bernd

```python
Python 2.7.8 (default, Jul  4 2014, 13:08:34) 
[GCC 4.9.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifc_wrapper
>>> i=ifc_wrapper.open("/home/hugo/Desktop/1549-IfcStructuralSurfaceMember.ifc")
>>> ss=ifc_wrapper.create_shape(i.by_id(1549))
>>> ss
''
```

**Comment by aothms** [comment]
Hi Bernd,

It has been a (long, long) while. Not sure if you are still pursuing this. With the latest commit in the svn repo [1] it is now possible for IfcOpenShell to extract this information. Both for shape- as well topological representations lines can be emitted, as long as the correct settings are specified (INCLUDE_CURVES, EXCLUDE_SOLIDS_AND_SURFACES). The create_shape() function has been given an additional optional argument to specify a representation explicitly, which is otherwise derived from the settings. For example to get the Axis representation in case of a wall (still INCLUDE_CURVES must be set in that case).

Also ccing @yorikvanhavre

[1] https://sourceforge.net/p/ifcopenshell/svn/348/

Kind regards,
Thomas

**Comment by berndhahnebach** [comment]
Hi Thomas, what a pleasant news. :-) .  I have put it on hold. But there is currently some heavy development in the regard of FEM in FreeCAD. As soon as the FEMWB in FreeCAD is sufficient for some basic calculationts I will start again trying to import my calculations by using Ifc_StructuralAnalysisView. If I have a minute I am gone test it and report back. 

Kind regards, Bernd.
